[package]
name = "web-sockets"
version = "0.1.0"
authors = ["Wolf van der Voorn"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.15"
futures = "0.3"
log = "0.4"
env_logger = "0.9"
